const actions = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    ADD_DELIVERY_COST: 'ADD_DELIVERY_COST',
    
    PURCHASE_ON: 'PURCHASE_ON',
    PURCHASE_OFF: 'PURCHASE_OFF',
    
    PURCHASE_INIT: 'PURCHASE_INIT',
    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILURE: 'PURCHASE_BURGER_FAILURE',
    
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',

    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    AUTH_LOGOUT: 'AUTH_LOGOUT'
}

export default actions;