const actions = {
    ADD_INGREDIENT: 'ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
    SET_INGREDIENTS: 'SET_INGREDIENTS',
    FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED',
    ADD_DELIVERY_COST: 'ADD_DELIVERY_COST',
    INIT_INGREDIENTS: 'INIT_INGREDIENTS',
    
    PURCHASE_INIT: 'PURCHASE_INIT',
    PURCHASE_BURGER_START: 'PURCHASE_BURGER_START',
    PURCHASE_BURGER_SUCCESS: 'PURCHASE_BURGER_SUCCESS',
    PURCHASE_BURGER_FAILURE: 'PURCHASE_BURGER_FAILURE',
    PURCHASE_BURGER: 'PURCHASE_BURGER',
    
    FETCH_ORDERS_START: 'FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS: "FETCH_ORDERS_SUCCESS",
    FETCH_ORDERS_FAILURE: 'FETCH_ORDERS_FAILURE',
    FETCH_ORDERS: 'FETCH_ORDERS',

    AUTH_START: 'AUTH_START',
    AUTH_SUCCESS: 'AUTH_SUCCESS',
    AUTH_FAILURE: 'AUTH_FAILURE',
    AUTH_CHECK_TIMEOUT: 'AUTH_CHECK_TIMEOUT',
    AUTH_LOGOUT: 'AUTH_LOGOUT',
    AUTH_INIT_LOGOUT: 'AUTH_INIT_LOGOUT',
    AUTH_USER: 'AUTH_USER',
    AUTH_CHECK_STATUS: 'AUTH_CHECK_STATUS',
}

export default actions;